version: "3.9"
services:
  db:
    image: postgres:14.2
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    entrypoint:
      - sh
    command:
      - -c
      - |
        [ -f ~/.exec-once ] || {
          yarn && yarn prisma db push && yarn prisma db seed && touch ~/.exec-once
        }
        yarn dev
